auto:					true
permalink:				/:categories/:title
production_url:			http://jefffis.github.io/prose-test/
plugins:				./_plugins
layouts:				./_layouts
destination:			./_site
include:				['.htaccess']
exclude:				[]