auto:					true
#permalink:				/:categories/:title
permalink:				date
baseurl:				/prose-test/
baseurlsans:			/prose-test
plugins:				./_plugins
layouts:				./_layouts
destination:			./_site
include:				['.htaccess']
exclude:				[]